### ISSUE TITLE
Are you open to suggestions/issues?

### ISSUE THREAD

**Issue by Fuitad** [webalternative/phpWhois#1]
Hey there!

With the original phpWhois being pretty much abandonned, I gave your repo a shot but I'm hitting some little issues with php 7.1. I would gladly report them to you and help you fix them but before I do so, I'd like to know if you're OK with these reports or not.

Let me know! :)

**Comment by WorkingClassKid** [comment]
Hi! 
  Sure, I'm open to merge any pull request for bug fixes, additionnal TLDs, etc.. and try to fix the script if I can...

Regards,

**Comment by WorkingClassKid** [comment]
BTW, your github profil tell me you are from Montréal... Alors nous pouvons surement parler en français dans nos échanges au besoin ;)

**Comment by Fuitad** [comment]
Je ne comprends pas... est-ce que le code fonctionnait pour vous? Car aucun test ne semble passer dans master (avant mon PR) et les fichiers .gtld.registrar ne semble pas être utilisés. C'est normal?
